### ISSUE TITLE
Unknown Architecture Raspberry Pi 4

### ISSUE THREAD

**Issue by WilsontheWolf** [Randomblock1/checkra1n-linux#1]
```sh 
pi@raspberry:~ $ sh getcheckra1n.sh 
System Architecture: armv7l
getcheckra1n.sh: 38: getcheckra1n.sh: [[: not found
getcheckra1n.sh: 38: getcheckra1n.sh: armv7l: not found
getcheckra1n.sh: 42: getcheckra1n.sh: [[: not found
getcheckra1n.sh: 46: getcheckra1n.sh: [[: not found
getcheckra1n.sh: 50: getcheckra1n.sh: [[: not found
Unknown/Unsuported architecture! Exiting... 
```
from what i understand it should work. Please correct me if I'm wrong

**Comment by WilsontheWolf** [comment]
actually manually modifying the arch doesn't seem to work either

**Comment by Randomblock1** [comment]
I pushed a fix that should work, tell me how it goes

**Comment by WilsontheWolf** [comment]
I manually installed it using the code but I can try reinstalling it. 
It turns out you also need to install `usbmuxd` for checkra1n which worked fine with an apt install for me, so maybe install this automatically.
I'll reinstall the thing and see if it works

**Comment by WilsontheWolf** [comment]
nope still broken 
```
pi@raspberry:~ $ sh getcheckra1n.sh 
System Architecture: armv7l
getcheckra1n.sh: 38: getcheckra1n.sh: [[: not found
getcheckra1n.sh: 38: getcheckra1n.sh: armv7l: not found
getcheckra1n.sh: 42: getcheckra1n.sh: [[: not found
getcheckra1n.sh: 42: getcheckra1n.sh: *armv*: not found
getcheckra1n.sh: 46: getcheckra1n.sh: [[: not found
getcheckra1n.sh: 50: getcheckra1n.sh: [[: not found
Unknown/Unsuported architecture! Exiting...
```

**Comment by Randomblock1** [comment]
I think I figured it out.
Don’t use sh (file), do this instead:
Make sure the file is executable with a chmod 755 script.sh
Then, type ./script.sh in your terminal
This is how you execute scripts properly in Linux

**Comment by Randomblock1** [comment]
I also fixed a silly mistake in there, so try and redownoad it.

**Comment by WilsontheWolf** [comment]
It Worked thanks
