### ISSUE TITLE
Install usbmuxd in script

### ISSUE THREAD

**Issue by WilsontheWolf** [Randomblock1/checkra1n-linux#2]
I mentioned it in #1 but checkra1n requires `usbmuxd` to work, so it would make sense to install it in the script.

**Comment by Randomblock1** [comment]
Good start, but we have to make sure the system is running Debian before attempting to install with apt. For instance, what if they’re using arch, red hat, etc?
I’ll work on this soon

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by WilsontheWolf** [comment]
well the pr i made is for the deb one. not sure for the other ones

**Comment by Randomblock1** [comment]
wait holdup I just realized the script you edited was made for apt systems. And installing checkra1n via apt automatically installs dependencies. So I’m going to close it, but keep the issue open so I can add dependency installing in a separate script for all systems

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by WilsontheWolf** [comment]
ok

**Comment by ghost** [comment]
> Good start, but we have to make sure the system is running Debian before attempting to install with apt. For instance, what if they’re using arch, red hat, etc?
> I’ll work on this soon
> 
> Sent with [GitHawk](http://githawk.com)

yeah but doesnt like arch come with libusbmuxd installed already? and who is gonna use enterprise level linux distros (e.g red hat) for ios jailbreaking?

**Comment by ghost** [comment]
i mean couldnt you do something like the architecture detection thingy for installing but instead of checking architecture it looks for the distro and if it matches like arch based one (e.g manjaro) to run  `pacman -S libusbmuxd` or smth of the sort?

**Comment by Randomblock1** [comment]
Yes I could, however I have no idea what the other package managers are, I only know apt. I need to test the others and see if the dependencies have the same names.

**Comment by ghost** [comment]
i mean they should be the same

**Comment by Randomblock1** [comment]
Finally added it

**Comment by ghost** [comment]
oh poggers
